### ISSUE TITLE
[Readme: Arch Linux Installation] Is updating the system intended?

### ISSUE THREAD

**Issue by Emily3403** [lapce/lapce#1029]
In the Readme the installation of the Arch Linux package is described as follows
```bash
sudo pacman -Syu lapce
```

This command has the side-effect to update the entire system and in my case downloading 300 MiB and installing 1 GiB while also downloading and installing the `lapce` package.

Is there any benefit of updating the entire system instead of simply installing the package with the following?
```bash
sudo pacman -S lapce
```

**Comment by dimitris-triantafyllidis** [comment]
It is just a matter of good practice. You can only download the latest version of a package with -S, so if you do not update the rest of the system as well you might be unlucky and face an incompatibility issue.

Since a text editor is not a critical part of the system just use -S and do a full update if you face issues or whenever you would normally do it.

**Comment by panekj** [comment]
[Partial upgrades are not supported.](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported)
