### ISSUE TITLE
CTRL+s is laggy

### ISSUE THREAD

**Issue by leocrapart** [lapce/lapce#1128]
## Lapce Version
0.2.0

## System information
Windows 10

## Describe the bug
When I press CTRL+s to save a file, it takes 1 second to save the file (to see the white dot disapearing).

I open this issue because according to the website "any lag on your keystroke will be treated as a bug and get fixed."

**Comment by MinusGix** [comment]
Do you only experience this with files where you have a language server plugin for that file? (Ex: the Rust plugin for Rust files). If so, then it could be delay due to the LSP doing various things (such as deciding whether/how to format the document) and so causing the delay.  
If it happens on most files, does it tend to occur on really big files or does it seem to have a noticeable delay on most files?

**Comment by ts-vadim** [comment]
For me it happens when I open new rust project and start editing source files while LSP is "fetching metadata".

**Comment by sokorototo** [comment]
I think it's the format on save that is causing the delay. You could turn it off, as it's the only operation that is called explicitly before saving. IMO it should be off by default

**Comment by tzAcee** [comment]
Was experiencing the same on windows 10 and thought it was system behaviour somehow. As I installed lapce on my linux notebook the delay was not a thing.
On my Windows machine are no plugins installed. On Linux Im running the Rust plugin.

**Comment by tzAcee** [comment]
Looks like the event is not getting set, as soon as the get_document_formatting is finished/not finished.
I testwise set the receive limit to 10ms, to verify it. The delay is now much smaller accordingly.
![image](https://user-images.githubusercontent.com/50580688/190898602-9814d10e-0a3c-48f2-8354-694f41bd2005.png)

I'll try to get it fixed via PR, while the max timeout stays at 1 second of course.
