### ISSUE TITLE
[FIXED] Code Completion/Highlighting doesn't work on Rust files created from the editor

### ISSUE THREAD

**Issue by PaperSlayer69** [lapce/lapce#1204]
## UPDATE
Turns out I have to put `mod (file name);` in the main file... my bad

## Lapce Version

v0.2.0

## System information

Windows 10

## Describe the bug
Creating a .rs file from the editor will disable code completion and highlighting in that file for some reason...
You would have to create it in vscode, quit then open lapce again.

## Additional information
- screenshot
![Capture](https://user-images.githubusercontent.com/92044996/190205034-3e7f79f1-cde0-4060-b0ee-945595d4824c.PNG)

**Comment by bugadani** [comment]
Rust analyzer likes to complain if a file is not part of the module tree, but you should still see tree-sitted highlighting even so, I believe.

I actually can't reproduce your issue - I created a new file in a project, and I get highlighting just fine.
![image](https://user-images.githubusercontent.com/977627/190252986-29b888d6-1a6f-421b-a134-13592c00c1ce.png)

Maybe this issue was fixed after the 0.2.0 release. Can you please try a nightly build? You can download one from the newest (upmost) run from this list: https://github.com/lapce/lapce/actions/workflows/release.yml
