### ISSUE TITLE
Add mosh support

### ISSUE THREAD

**Issue by notorand-it** [lapce/lapce#138]
https://mosh.org/

Users on the move will be happy!

**Comment by evantd** [comment]
This is not something mosh can support, since it doesn't support port forwarding. This is also part of the reason mosh doesn't support ssh-agent and why you can't use it for VSCode. See https://github.com/mobile-shell/mosh/issues/1111.

From some of the comments on related mosh issues, it sounds like https://eternalterminal.dev/ might be a good compromise between the roaming of mosh and the features of ssh.

**Comment by panekj** [comment]
As noted, `mosh` is not possible for us to support.

**Comment by d21d3q** [comment]
`mosh` could be used in combination with ssh. mosh for remote terminal (snappiness), and ssh for port and agent forwarding.

**Comment by notorand-it** [comment]
I am not sure this complication will be really useful. 

With ssh you already have full remote editing along with terminal.

With mosh you will only get more responsive terminal at the cost of extra firewalling configuration and complication within editor code.

**Comment by d21d3q** [comment]
Not only roaming, but as website states: 
> Remote terminal application that allows roaming, supports intermittent connectivity, and provides intelligent local echo and line editing of user keystrokes.

That latter part is where it shines. Especially when you work on remotely on crappy cellular connection, on train etc.  
On ssh terminal just freezes and your keystrokes are buffered (but not shown locally, maybe eventually they will be sent before your session drops. Or not.  

With mosh you can see local echo, and you can be sure that it will connect successfully when it comes back. With ssh you never knows (and tries to ctrl-d it and reconnect and re-temux to your session). 

According to firewall, probably. I work over tailscale so that solves that issue for me.
