### ISSUE TITLE
Rust LSP not working On MacOS

### ISSUE THREAD

**Issue by kotlin2018** [lapce/lapce#1494]
## Lapce Version
![image](https://user-images.githubusercontent.com/56008171/195497415-5ea2354c-522d-4818-a593-a0a72a6894b8.png)

## System information
![image](https://user-images.githubusercontent.com/56008171/195497588-e2f1e8cf-0e48-4d7f-9c21-c36e7056dd91.png)

rustc --version 1.64.0

## Describe the bug
The LSP doesn't appear to be working, I have no squiggly lines, when I press F12 nothing happens, etc

## Additional information
Write code in the trust file without code intelligence prompt and code jump.

**Comment by hbina** [comment]
Have you updated your plugin?

**Comment by kotlin2018** [comment]
This is my rust plugin

![image](https://user-images.githubusercontent.com/56008171/195506546-192cffc1-3dcf-41a5-84c8-d69b3476af9d.png)

**Comment by peterje** [comment]
+1 for this, I have not been able to get any LSP to work on my m1 Macbook pro.

**Comment by 4gboframram** [comment]
+1 i can't get any lsp to work on my linux machine either

**Comment by MinusGix** [comment]
Via Cmd+Shift+p/Ctrl+Shift+p (or clicking the top bar and typing the `:` prefix) you can open the command palette. Then, you can use the 'Open Logs Directory'. Uploading a log from when you start the editor and try doing something (ex: typing in a rust file) would be useful, since it could tell us how Rust Analyzer is failing.   
(Note: Make sure the current log file has text; you may have to exit out of the editor to get it to flush to the file)

**Comment by ranger-ross** [comment]
I was having the same issue but fixed it by deleting `/Users/$USER/Library/Application Support/dev.lapce.Lapce-Stable` and re-installing Lapce. I am wondering if it was possibly due to a stale file(s) from when i upgraded from `0.2.0` to `0.2.1`
