### ISSUE TITLE
Why I haven't switched to Lapce (some feature requests)

### ISSUE THREAD

**Issue by lylythechosenone** [lapce/lapce#1987]
I really like Lapce. It's a nice idea, and it works really well. However, I have a few concerns stopping me from actually switching to it from VSCode.

Firstly, the preferences panel is lacking in a lot of ways. There are little code inserts like below that are impossible to disable from what I can tell. There are also no dropdown menus in the settings, and also no list of correct/possible values. All of these small issues together contribute to a less intuitive experience.
![image](https://user-images.githubusercontent.com/19551513/212362168-06f19c2c-a4db-47f2-85cc-c655bf4627f7.png)

Secondly, there are no animations anywhere, making the whole software feel less finished. In VSCode, for example–when installing an extension, the "Install" button changes to "Installing" and then changes to a blue "Uninstall." A blue progress bar also appears on the extension panel, clearly denoting that something is actually happening.

Lastly, a few buttons just don't work (I suppose these should be bug reports).

I see a lot of hope in Lapce, and I may switch to it in the future, but these issues really make it a harder choice over VSCode. I'd love to help implement any of these features if needed (I've never used Druid, but I mainly code in rust and I've used similar libraries before).

**Comment by panekj** [comment]
> Firstly, the preferences panel is lacking in a lot of ways.

This is being worked on constantly.

> There are also no dropdown menus in the settings

They are implemented in `master` branch.

> Secondly, there are no animations anywhere, making the whole software feel less finished. In VSCode, for example–when installing an extension, the "Install" button changes to "Installing" and then changes to a blue "Uninstall." A blue progress bar also appears on the extension panel, clearly denoting that something is actually happening.

We have progress indicator and plugin moves from `Available` to `Installed` section after installation.
![image](https://user-images.githubusercontent.com/50457605/212365808-5bde1913-59de-4b51-8d8d-33cc97893679.png)


> Lastly, a few buttons just don't work (I suppose these should be bug reports).

Yes

I'll close this since this isn't a specific bug report and we have better issues open for mentioned issues.
Also please note that Lapce is in active development and is not ready for widespread usage, we will work on UI/UX once we get closer to completing editor backend.
