### ISSUE TITLE
Create Dev Container to have an stable contributing environment

### ISSUE THREAD

**Issue by FarzinVatani** [lapce/lapce#2235]
## Is your feature request related to a problem? Please describe.

New contributors need to install bunch of libraries and maybe they develop on windows and it may be a little hard to work around.

## Describe the solution you'd like

So a universal development environment like docker development container is a good idea to start developing fast.

**Comment by panekj** [comment]
Lapce is a graphical application so running it in container is not supported, it also puts maintainence burden on us to keep devcontainer up-to-date.

**Comment by nikaro** [comment]
I think the idea of this issue was more to support something like [VSCode DevContainer](https://containers.dev). This is a really nice things as it allows to declaratively configure your development environment and share it easily. No need to install LSP servers, linters, compilers, and whatever on your machine. It installed/started when you start your IDE.
