### ISSUE TITLE
Client sent workspace folders despite not declaring - Terraform plugin

### ISSUE THREAD

**Issue by itsezc** [lapce/lapce#2241]
## Lapce Version

0.2.6

## System information

Windows 11 with WSL 2 (Ubuntu)

## Describe the bug

Installed (a fresh instance of) Lapce, and the Terraform plugin and immediately a dialog opened, the syntax highlighting seems to work.

## Additional information

![image](https://user-images.githubusercontent.com/33750251/224653973-0e0d085e-80e0-462b-a276-a4966e454f14.png)

This dialog pops up even after restarting Lapce and WSL. The dialog wasn't clear as to whether it was an issue with the plugin or Lapce, so I've opened an issue here, happy to move it to the relevant repository if necessary.

I have a monorepo setup (perhaps this could be an issue?)

**Comment by da-moon** [comment]
I did some debugging.

The following is an the two requests that `terraform-ls` received which caused an error

- Request 1

```json
{
  "capabilities": {
    "textDocument": {
      "codeAction": {
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports",
              "quickassist",
              "source.fixAll"
            ]
          }
        },
        "dataSupport": true,
        "resolveSupport": {
          "properties": [
            "edit"
          ]
        }
      },
      "completion": {
        "completionItem": {
          "resolveSupport": {
            "properties": [
              "additionalTextEdits"
            ]
          },
          "snippetSupport": true
        }
      },
      "definition": {},
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "inlayHint": {},
      "publishDiagnostics": {},
      "semanticTokens": {
        "formats": [],
        "requests": {},
        "tokenModifiers": [],
        "tokenTypes": []
      },
      "signatureHelp": {
        "signatureInformation": {
          "activeParameterSupport": true,
          "documentationFormat": [
            "markdown",
            "plaintext"
          ],
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "synchronization": {
        "didSave": true,
        "dynamicRegistration": true
      },
      "typeDefinition": {
        "linkSupport": false
      }
    },
    "window": {
      "showMessage": {
        "messageActionItem": {
          "additionalPropertiesSupport": true
        }
      },
      "workDoneProgress": true
    },
    "workspace": {
      "configuration": false,
      "symbol": {}
    }
  },
  "clientInfo": {
    "name": "Lapce-Stable",
    "version": "v0.3.1"
  },
  "processId": 115997,
  "rootUri": "file://<ABSOLUTE-PATH-TO-TF-MODULE-DIR>/",
  "trace": "verbose",
  "workspaceFolders": [
    {
      "name": "file://<ABSOLUTE-PATH-TO-TF-MODULE-DIR>/",
      "uri": "file://<ABSOLUTE-PATH-TO-TF-MODULE-DIR>/"
    }
  ]
}
```

- Request 2

```json
{
  "capabilities": {
    "textDocumentSync": {
      "openClose": true,
      "change": 2,
      "save": {}
    },
    "completionProvider": {
      "triggerCharacters": [
        ".",
        "["
      ],
      "resolveProvider": true,
      "completionItem": {}
    },
    "hoverProvider": true,
    "signatureHelpProvider": {},
    "declarationProvider": {},
    "definitionProvider": true,
    "referencesProvider": true,
    "documentSymbolProvider": true,
    "codeActionProvider": {
      "codeActionKinds": [
        "source.formatAll.terraform"
      ]
    },
    "codeLensProvider": {},
    "documentLinkProvider": {},
    "workspaceSymbolProvider": true,
    "documentFormattingProvider": true,
    "documentOnTypeFormattingProvider": {
      "firstTriggerCharacter": ""
    },
    "executeCommandProvider": {
      "commands": [
        "terraform-ls.module.callers",
        "terraform-ls.module.calls",
        "terraform-ls.module.providers",
        "terraform-ls.module.terraform",
        "terraform-ls.rootmodules",
        "terraform-ls.terraform.init",
        "terraform-ls.terraform.validate"
      ],
      "workDoneProgress": true
    },
    "semanticTokensProvider": {
      "legend": {
        "tokenTypes": [],
        "tokenModifiers": []
      },
      "full": false
    },
    "workspace": {
      "workspaceFolders": {
        "supported": true,
        "changeNotifications": "workspace/didChangeWorkspaceFolders"
      }
    },
    "experimental": {
      "referenceCountCodeLens": false,
      "refreshModuleProviders": false,
      "refreshModuleCalls": false,
      "refreshTerraformVersion": false
    }
  },
  "serverInfo": {
    "name": "terraform-ls",
    "version": "0.29.1"
  }
}
```

Based on this request, Here is what I was able to find :

- the error `terraform-ls` is returning is defined here: https://github.com/hashicorp/terraform-ls/blob/c553330e332d6e52a46ff5079b5d0002948f58fb/internal/langserver/handlers/initialize.go#L121
- it seems like `terraform-ls` expects the following:
  - When `request.capabilities.workspace.workspaceFolders` exists, `request.workspaceFolders` should exist and not be an empty array
   - as you can see, in the second request, `request.workspaceFolders` array does not exist
- `~/.local/share/lapce-stable/plugins/panekj.lapce-terraform-ls/volt.toml` is where language-server config resides. it seems like in this file, you can customize any server launch property that starts with `options.*` prefix as defined in terrafom-ls [`getTelemetryProperties`](https://github.com/hashicorp/terraform-ls/blob/c553330e332d6e52a46ff5079b5d0002948f58fb/internal/langserver/handlers/initialize.go#L194) function
  - To be more specific, it looks like you can't customize lsp capabilities.
- it seems like `lapce-proxy` uses [`client_capabilities()`](https://github.com/lapce/lapce/blob/83120215adab125b065ed50a62aa21a4b74d375f/lapce-proxy/src/plugin/mod.rs#L1392) function to prepare the request payload so I suspect that we would need to do one of the following:
  - modify this  [`client_capabilities()`](https://github.com/lapce/lapce/blob/83120215adab125b065ed50a62aa21a4b74d375f/lapce-proxy/src/plugin/mod.rs#L1392) function so that it sends the required payload. This might be challenging as it would impact all other LSP servers
   - make necessary modification so that users can define custom `capabilities` payload in   `~/.local/share/lapce-stable/plugins/panekj.lapce-terraform-ls/volt.toml` or another config file.

**Comment by panekj** [comment]
https://github.com/lapce/lapce/commit/32d68b8a676876fb9c922e4c52efcfebbada6261
