### ISSUE TITLE
Plugin - Overwrite LSP capabilities

### ISSUE THREAD

**Issue by sharpSteff** [lapce/lapce#2312]
I'm working on a C#-Plugin for Lapce (using the Lapce-plugin-template) using the Omnisharp C# LSP.
However it seems in the current state Omnisharp is not fully LSP spec conform.
OmniSharp/omnisharp-roslyn/issues/2483

I have no clue where I can inject some kind of middleware to overwrite the capabilities which were sent back from the LSP

**Comment by hbina** [comment]
What you can do is to use the plugin as the middleware. Your plugin will initialize and talk to the C# LSP and then you do all the necessary transformation from within the plugin.

**Comment by sharpSteff** [comment]
you mean in 
`fn handle_request(&mut self, _id: u64, method: String, params: Value)`
I can do basically anything?

**Comment by hbina** [comment]
Yes. You receive a request from lapce, you send it to the LSP, you get something from the LSP, process/transform it as necessary, and pass it back to lapce.

**Comment by sharpSteff** [comment]
I think, I need a little help here.
It seems Lapce sends the capabilities directly to the LSP without the plugin.

I need to set the ClientCapabilities.publish_diagnostics, since the deserialization on LSP-Side crashes if the value is none.
However the LSP crashes nevertheless. 
If I change client_capabilities in 'lapce-proxy/src/plugin/mod.rs' to initialize the field with default values, the LSP does not crash and works fine
```
 publish_diagnostics: Some(PublishDiagnosticsClientCapabilities{
                ..Default::default()
 }),
```

```
fn handle_request(&mut self, _id: u64, method: String, params: Value) {
        #[allow(clippy::single_match)]
        match method.as_str() {
            Initialize::METHOD => {
                let mut params: InitializeParams = serde_json::from_value(params).unwrap();
                if let Some(td) = &mut params.capabilities.text_document {
                    if td.publish_diagnostics.is_none() {
                        td.publish_diagnostics = Some(PublishDiagnosticsClientCapabilities::default());
                    }
                }

                if let Err(e) = initialize(params) {
                    PLUGIN_RPC.stderr(&format!("plugin returned with error: {e}"))
                }
            }
            _ => {}
        }
    }
```

**Comment by hbina** [comment]
That is a bug on lapce side. Do you have the stack trace?

> It seems Lapce sends the capabilities directly to the LSP without the plugin.

This is true. As of now, plugins are mostly there to:

1. tell lapce what file types it is interested in for activation (like activate lsp when `Cargo.toml` is detected).
2. figure out where the path to the LSP is so that lapce can execute it (via `PLUGIN_RPC.start_lsp`)

So yes, most of the time, lapce talks to the LSP directly because there's no need for a middleman.

Also, the code snippet that you mentioned does not make sense.
What you got from `params` in `let mut params: InitializeParams = serde_json::from_value(params).unwrap();` is lapce telling you what _lapce_ is capable of. You then respond via `PLUGIN_RPC.host_success` by telling lapce what _you_ are capable of. Mutating the `params` here does nothing. If `lapce` says that it does not support it, then there's not much that you can do. If you report back to the C# LSP that lapce supports it when it doesn't then....lapce will likely just ignore it or do something bad with it.

If you would like it to be supported, perhaps you can tell me more what you wanted to do? Maybe I can take a look at it.

I am not sure what `initialize` does here.

**Comment by sharpSteff** [comment]
I thought I could modify what _Lapce_ is capable of before passing the params to the LSP. 

I opened an issue at ionide/LanguageServerProtocol#47
Stacktrace is a little difficult, the only log entry I got is:
`[2023-04-02][01:16:56][lapce_data::proxy][ERROR] lsp server csharp-ls stopped! missing content-length header: `


I could track it down to 
`client_capabilities` in 'lapce-proxy/src/plugin/mod.rs'

by extending the Initializer of ClientCapabilities:
```
            definition: Some(GotoCapability {
                ..Default::default()
            }),

// Missing field
            publish_diagnostics: Some(PublishDiagnosticsClientCapabilities{
                ..Default::default()
            }),
// --------------------------------
            ..Default::default()
```

**Comment by hbina** [comment]
` [2023-04-02][01:16:56][lapce_data::proxy][ERROR] lsp server csharp-ls stopped! missing content-length header: ` indicates that that LSP is not responding using the proper LSP format. I wonder what it is sending instead?

**Comment by sharpSteff** [comment]
Nothing. The buffer is empty. The LSP right up crashed, when receiving the jsonrpcmessage with not publish_diagnostics set

**Comment by sharpSteff** [comment]
@hbina I think we can close this issue. I got me fix for the lsp merged, so everything is fine now 😃
