### ISSUE TITLE
Typst support

### ISSUE THREAD

**Issue by LuckyTurtleDev** [lapce/lapce#2330]
It would be nice if Lapce does support Typst.
https://typst.app/

**Comment by LuckyTurtleDev** [comment]
Looks like it exist already a language server for typst:
https://github.com/nvarner/typst-lsp

**Comment by MinusGix** [comment]
The LSP would most likely not be hard for someone to make a plugin out of.   
Features like live-preview of the document (like on the typst website's video) can't be implemented with plugins currently.

**Comment by trevnels** [comment]
Currently taking a shot at implementing this. I have a plugin loading which can download the lsp, but I still need to figure out how to actually register the language with lapce and have its file extension be recognized.

**Comment by trevnels** [comment]
![image](https://github.com/lapce/lapce/assets/25140503/ad2e2725-890c-4e4f-84f4-b45fc111d044)
Looks like LSP completion is working, but there's a few quirks, namely placeholders aren't being handled properly:
![image](https://github.com/lapce/lapce/assets/25140503/a931843e-dafc-45c6-8a73-0970c1f2a12b)
PDF exporting also doesn't seem to be happening. The LSP may need to be sent some commands for this to function, but can just use the typst CLI for now.

Currently hijacking the markdown file type for the LSP - will need to modify lapce itself to recognize typst as a language before publishing anything, since it currently means markdown won't work. May fork and try to do this at some point, which would also get syntax highlighting working.

**Comment by panekj** [comment]
Closing since this should be handled as plugin
