### ISSUE TITLE
cargo vendor fails to sync - duplicate version of package

### ISSUE THREAD

**Issue by kekePower** [lapce/lapce#2452]
## Lapce Version

Git master.
I downloaded a fresh copy and see the message below.

## System information

Mageia Cauldron x86_64

## Describe the bug
```
% cargo vendor > .cargo/config
error: failed to sync

Caused by:
  found duplicate version of package `swash v0.1.6` vendored from two sources:

  	source 1: registry `crates-io`
  	source 2: https://github.com/dfrg/swash#af0c735d
```
```
% cargo --version
cargo 1.70.0
```

## Additional information

N/A

**Comment by MinusGix** [comment]
I expect that this is due to us having `lapce-app` and `lapce-data`/`lapce-ui`.  
`lapce-app` is our current version rewritten with the new UI library, while `lapce-data`/`lapce-ui` are the old versions which used druid. We are currently keeping them around to make it easier to port parts of code that we've missed reimplementing.  
They both depend on swash but different versions like the error message says. However, they don't interact at all (so we aren't actually depending on two different versions).  

I did a quick skim of cargo vendor's docs, and I don't see a good way to avoid this. There's also https://github.com/rust-lang/cargo/issues/10310.

But you can just vendor whichever one you're wanting to work on / use.  
  
If you're wanting to contribute to master, or use the current master, then removing `lapce-data`/`lapce-ui` and adjusting the `Cargo.toml` workspace should let you vendor it.  
  
If you're wanting to vendor the older druid version, then doing the same to `lapce-app` should work. Though you'll run into #2463 

----

We'll remove the `lapce-data`/`lapce-ui` folders in the future once we have gotten 'enough' of the pieces ported over.

**Comment by panekj** [comment]
Fixed with https://github.com/lapce/lapce/commit/774008f54bc5843afa8cbf8fa766b620c545aa27
