### ISSUE TITLE
Lapce does not cooperate with system clipboard and appears to use its own internal one

### ISSUE THREAD

**Issue by alexpyattaev** [lapce/lapce#2787]
## Lapce Version

Lapce v0.3.0 
Nightly 8dc41a0 

## System information

Arch x86_64, KDE wayland 

## Describe the bug
When I copy text into clipboard (via middle mouse button or keyboard hotkey) in any other application, the text can then be pasted as usual (with middle mouse or keyboard hotkey). When I copy text in Lapce (via hotkey) it can then be pasted in lapce (via hotkey). However, there appears to be no connection between lapce clipboard and system clipboard, i.e. text copied from another app can not be pasted into lapce and vice versa.  

## Additional information
I have seen similar issues on other KDE setups. The issue does not seem to occur on Ubuntu desktop with same version of Lapce. 
If necessary I can try to investigate this further but I have no idea what to look for - there are no errors in any logs that I can see.

**Comment by dvaerum** [comment]
I am having the same experience, I am on version v0.3.0, just to say that you are not alone :sweat_smile:

**Comment by MinusGix** [comment]
I'm seeing this on Sway as well, so it isn't strictly KDE probably.

**Comment by lukaslihotzki** [comment]
This is related to #2768 and is caused by Lapce only supporting the X11 clipboard, not the Wayland clipboard. So, Lapce runs its window on Wayland, but opens an extra connection to X11 for the clipboard.

I propose that Lapce should do what Alacritty does, because the Alacritty clipboard works well on Wayland and it also uses winit and copypasta. This would be done by copying the [clipboard.rs file](https://github.com/alacritty/alacritty/blob/master/alacritty/src/clipboard.rs) from Alacritty to Lapce and use that instead of `ClipboardProvider::new()`. Also, we would need the `RawDisplayHandle` from winit (or floem) to pass it to clipboard.rs.

**Comment by alexpyattaev** [comment]
I would have never guessed it is even possible to use X11 clipboard from wayland app... I'd be happy to test any fix if that would help but I'm certainly not qualified to implement this.

**Comment by lukaslihotzki** [comment]
@alexpyattaev, then please test the fix in #2815.

**Comment by alexpyattaev** [comment]
Thank you for addressing this!
