### ISSUE TITLE
Weird keybindings behaviour using Colemak

### ISSUE THREAD

**Issue by WeetHet** [lapce/lapce#2800]
On macOS (and linux probably?) the keybindings are weird for colemak. Instead of using real keystrokes, lapce seems to use "places" on the keyboard. For example to press Cmd+N and create a new file, one should press Cmd+K, as the position of K in Colemak coincides with position of N in QWERTY. This should be changed, so lapce would use real key inputs and not their places

**Comment by joshkamm** [comment]
This looks related to #2731

**Comment by starchyunderscore** [comment]
Same on arch linux, kde plasma, wayland, using dvorak. It also does not respect key rebindings (ex: caps -> backspace), simply ignoring the keypress entirely.

**Comment by theherk** [comment]
I'm confused by your wording, but I think I am suffering from a similar problem. I would think to push `⌘ n` to open a new file I would push `⌘ n` which would be `⌘` and the letter with a "J" printed on it; where the "n" in Colemak actually is. I'm frustrated by `hjkl` being `hnei` instead of `hjkl` or the keys printed `hynu`. If the keybindings say `hjkl`, they should work with the keys `hjkl`.

**Comment by dzhou121** [comment]
This is potentially fixed by https://github.com/lapce/lapce/pull/3119

Can you please test the latest nightly build

**Comment by mips171** [comment]
> This is potentially fixed by #3119
> 
> Can you please test the latest nightly build

Yes it is working. I use Dvorak layout btw
