### ISSUE TITLE
find (e.g. ctr+f)  freezes after one use

### ISSUE THREAD

**Issue by lineality** [lapce/lapce#3012]
## Lapce Version
Lapce nightly

## System information

fedora 39
dell inspiron

## Describe the bug
find (e.g. ctr+f)  freezes after one use
needs to be restarted

## Additional information
the replace function never works, can't ever add text into it

Other information that can be used to further reproduce or isolate the problem.
- workarounds that you used

I just have to close and open it again but it is very frustrating and prone to injecting typos into the code
because I can never tell where the text will appear.

ctr+d is a life-saver and usually works well, main reason why I use Lapce as my main editor.

**Comment by MinusGix** [comment]
Reproducing instructions since it took me a bit to get what the issue meant, I'll make a PR for this:
- Ctrl + F
- type something like "Vec"
- Press enter and you can go forward between the different selections
- click off the find input, such as into the editor
- click back into the find input, enter no longer works to move between entries and you can't type in it
