### ISSUE TITLE
Terminal default profile dropdown breaks config

### ISSUE THREAD

**Issue by aalhitennf** [lapce/lapce#3070]
## Lapce Version
debug - git master commit 8127fc25ce88c92bea78af5a32b0f57e81d483ca

## System information
Linux

## Describe the bug
Opening `Terminal: Default Profile` dropdown from settings and clicking `default` "corrupts" settings.toml and resets all settings to default.

## Additional information
Setting is written like this to `settings.toml`:
```
[terminal]
default-profile = "default"
```
so it can't be deserialized to `HashMap<String, String>` which should be the type of the field in `TerminalConfig` struct. That breaks the whole config and lapce uses defaults instead of values from settings.toml content.

**Comment by maddes8cht** [comment]
At least on  my windows 10 it isnot possible to select anything else than "default" in the "terminal default profile" setting, as it is the last setting on the settings page, and the dropdown items are always cut of, so that they cannot be reached with the mouse. I also tried several combinations of keystrokes to access the list, like cursor down, shift- ctrl - and alt- combinations, tab etc., but none of these makes the dropdown items available.
![grafik](https://github.com/lapce/lapce/assets/55592906/651f4c74-b335-4790-b34e-1a14f0119e81)
