### ISSUE TITLE
How to close Editor Tab via Keyboard Shortcut (Ctrl + W)

### ISSUE THREAD

**Issue by elibroftw** [lapce/lapce#3176]
## Lapce Version

v0.3.1

## System information

Windows 11

## Describe the bug

Cannot close Editor tab via spotlight search nor via Ctrl + W.

## Additional information

![image](https://github.com/lapce/lapce/assets/21298211/6af6647e-47ea-4fdf-a4f8-3de7763f72a6)

No tooltip either

![image](https://github.com/lapce/lapce/assets/21298211/f8157d3d-83cc-4088-845b-8a246ea7230b)

**Comment by panekj** [comment]
The command is `Split Close`

**Comment by elibroftw** [comment]
That's not intuitive when the left side pane says "open editors" and not "open splits." Command should be called "Close Editor [Tab]". "Split Close" is something weird. Regardless, wouldn't need to know what it's called if the command was by default mapped to Ctrl + W.

**Comment by panekj** [comment]
> "Split Close" is something weird.

It's called split because editors can be split into multiple neighbouring editors.
![image](https://github.com/lapce/lapce/assets/50457605/163af2f3-066e-4958-b557-fa1ada73764a)


> Regardless, wouldn't need to know what it's called if the command was by default mapped to Ctrl + W.

It is mapped to `Ctrl` + `W`.
![image](https://github.com/lapce/lapce/assets/50457605/38718467-9ce1-4436-af03-104c2f001c9c)

**Comment by elibroftw** [comment]
It wasn't working for me for some reason and this was a fresh install too.
