### ISSUE TITLE
New fedora build from source instruction still not working and perl-core still needed (and not automatically included)

### ISSUE THREAD

**Issue by lineality** [lapce/lapce#3198]
## Lapce Version
'nightly' is all I can see displayed,
fresh git clone build from source 2024.04.24

## System information
fedora 40, dell xps laptop

## Describe the bug

New fedora build from source instruction still not working and perl-core still needed (and not automatically included)
https://github.com/lapce/lapce/blob/master/docs/building-from-source.md

1. perl-core is needed, otherwise there is an openssl(?) rust build error

2. the new build line 
```bash
cargo install --path . --bin lapce --profile release-lto --locked
```

does not work for creating a link in path, and a symbolic link cannot be made (a link file is made but it does nothing)

## Additional information
this does work (still)

```bash
sudo dnf install clang libxkbcommon-x11-devel libxcb-devel vulkan-loader-devel wayland-devel perl-File-Compare perl-FindBin perl-core
```

```bash
git clone https://github.com/lapce/lapce.git ~/lapce
```

```bash
cd lapce
```

this works
```bash
cargo build --release
```

Follow instructions below to set path to lapce, where path to 
lapce is like: 
```
home/YOURNAME/lapce/target/release/lapce
```

2.1  Install Perl (from official fedora source) to avoid a build-fail

https://developer.fedoraproject.org/tech/languages/perl/perl-installation.html
```bash
$ sudo dnf install perl-core
sudo dnf install perl-core
```

2.2 Create the ~/.local/bin directory
```bash
mkdir -p ~/.local/bin
```

2.3  Create a symbolic link:

   - Open a terminal and run the following command to create a symbolic link from the executable to the chosen directory:
```bash
ln -s home/YOURNAME/lapce/target/release/lapce ~/.local/bin/lapce
```

2.4  Add the directory to PATH (if necessary):
     ```bash
     export PATH="$PATH:$HOME/.local/bin"
     ```

2.5  Refresh the shell:
   - Run the following command to reload the shell configuration:
     ```
     source ~/.bashrc
     ```

Now you can call "lapce ." or "lapce --version" from cli

# Note: many thanks for work on lapce

Over the last few months lapce is really starting to mature into an amazing and use-able ide/editor. A huge thanks to everyone involved.

**Comment by MatthewScholefield** [comment]
FYI, I just ran the build instructions:
```
cargo install --path . --bin lapce --profile release-lto --locked
```
And it still failed on compiling openssl due to missing FindBin. I was able to get it working via:
```
sudo dnf install perl-File-Compare perl-FindBin perl-IPC-Cmd
```

Note that I needed the additional `perl-IPC-Cmd` package which wasn't mentioned in the build instructions before.

Note 2: Unsure if `perl-File-Compare` was required but the other two definitely were.

**Comment by panekj** [comment]
I removed the `perl` dependencies because they are not required (it's only needed for using vendored `openssl`). I've added `pkgconf` since that what could be missing on the system.

**Comment by MatthewScholefield** [comment]
I'm not sure I follow. What do you mean when you say they aren't required? Running the command on the build instructions does indeed require the perl dependencies. Is there some other command needed to specify not to use vendored openssl?

**Comment by ksaff** [comment]
I ran into this issue, too. To answer this question:

> Is there some other command needed to specify not to use vendored openssl?

There seem to be two options:

1. somehow disable the `vendored` feature
2. set `OPENSSL_NO_VENDOR=1`

> `OPENSSL_NO_VENDOR` - If set, always find OpenSSL in the system, even if the `vendored` feature is enabled.

https://docs.rs/openssl/latest/openssl/#manual

I set `OPENSSL_NO_VENDOR=1` and the build succeeded. I did not pay attention to the output, but I presume the OpenSSL crate successfully found the system OpenSSL.

For those of us with no experience with Rust and/or the OpenSSL crate, the current instructions in [building-from-source.md](https://github.com/lapce/lapce/blob/master/docs/building-from-source.md) are insufficient. I only figured this out because I stumbled across this issue: https://github.com/lapce/lapce/issues/967 which mentions the variable. 

I do not know enough to suggest changes with any confidence; whether to default to vendored or system openssl in the aforementioned doc file. The default in all the docker images seems to be system openssl. E.g. https://github.com/lapce/lapce/blob/master/extra/linux/docker/fedora/Dockerfile#L88. Maybe it's reasonable to simply add the setting of the variable to the `cargo install` line?
