### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by dzhou121** [lapce/lapce#558]
The next major thing for Lapce is plugin support. The plugin system is a critical part of a good code editor. We'd like Lapce's plugin API to be as flexible as possible. 

To start with, it would be helpful to know, what plugin you desperately need as a user, or what plugin API you would like as a potential Lapce plugin author, so that we can start to implement something that's immediately useful. 

Feel free to leave comments below for plugins(/APIs) you'd like. A link to a plugin in a different code editor would be fine.

**Comment by Vliro** [comment]
One major aspect that makes VSCode better than intellij is source control. Perhaps this doesn't need to be a plugin, but e.g. GitLens is a plugin and makes VSCode source control superior.

**Comment by Igigog** [comment]
Is it theoretically possible to add support for vscode plugins? Then vscode users will be as free as it gets to switch the editor, and lapce won't actually need plugin makers to be viable

**Comment by dzhou121** [comment]
> Is it theoretically possible to add support for vscode plugins? Then vscode users will be as free as it gets to switch the editor, and lapce won't actually need plugin makers to be viable

It would be very hard to do I think. There seemed to be an increasing interest to choose WASI for plugins, and I was thinking standardised plugin API similar to LSP. 

https://github.com/helix-editor/helix/issues/122#issuecomment-1092756752

**Comment by newcomertv** [comment]
As a user my list of features I need:
1. Linting (self explanatory) (includes colored brackets etc.)
2. Preview Window -> messing around with html/css, writing some markdown or latex, I need to see the final product while writing
3. File Navigation -> select file through spotlight search in current workspace
4. Snippets (self explanatory)
5. Some form of intelligent code completion -> ref. GithubCopilot
6. File History -> vscode has this neet feature that it saves intermediate saves before a  commit as backups you can roll back to for each file
7. themes (I like them ✨)
8.  Task system -> Wether manually added or automatically scanning for various build, debug or whatever tasks. if it's something I do a lot I want a button to run it inside my terminal.
9. Terminal as a tab instead of seperate object. -> have a setting to auto jump to terminal tab when running task in it (or not)
10. Integrated GUI for debugger -> ref. gdb and vscode
11. Hex Editor would be nice
12. Color preview for colorcodes in text
13. ...

**Comment by nheuillet** [comment]
Overall when it comes to plugins, I believe there are two kinds of capabilities:

- System-based: some plugins need to execute commands at some point (a git plugin invoking git, a Docker plugin interacting with docker using the CLI, etc.). **This is the easiest capability to add for immediate use**
*Do not that vscode allows arbitrary command execution, so it's not something new on our side*


- editor based: This is what the likes of VsCode offer mostly, and what needs to be decided.

A quick look at the [extensions capabilities for vscode](https://code.visualstudio.com/api/extension-capabilities/overview) shows these categories:
- Common Editor interactions
  - Registering commands, configurations, keybindings, or context menu items.
  - Storing workspace or global data.
  - Displaying notification messages.
  - Using Quick Pick to collect user input.
  - Open the system file picker to let users select files or folders.
  - Use the Progress API to indicate long-running operations.

- Theming
  - To my knowledge, this is the biggest change coming and you already started working on it so I won't dwell on it further.

- Workbench extensions
  - Adding new menus to the left bar. I am no expert with Druid but I fear this is probably gonna be one of the limiting factors, as with vscode you can easily write your HTML / CSS to extend, while it won't be the case here. 


Finally, looking at the [top install list](https://marketplace.visualstudio.com/search?target=VSCode&category=All%20categories&sortBy=Installs), the majority of the extensions are LSP servers or linting/highlighting extensions. 

Personally the extension I always installed first on vscode is bracket pair colorizer, and I believe Lapce would benefit from adding this kind of visual hints natively.

**Comment by MinusGix** [comment]
- The ability to display (styled) text 'inline' with the editor. This would allow things like [Error Lens](https://marketplace.visualstudio.com/items?itemName=PhilHindle.errorlens) and also things like showing the last commit that touched a line of code.  
  - Some extensions also provide clickable links in text, such as to show the implementations of an interface
- Basic styling of existing text within the editor. Such as custom underlines of a span, background highlighting, etc.
- Perhaps some form of (limited) communication between plugins?
- Notifications (like the in-corner ones vscode has) which provide a few options to deal with them.
- Popup notifications
- Basic custom UI support would be needed for some plugins, but I think a majority (of the small amount that actually need their own UI) can make do with some basic constructs like text/links/buttons/lists rather than the in-depth drawing that Druid performs.  
  - I think most common is perhaps 
  - As well, having the plugins hand over a structured list/tree of nodes is easier to manage instead of giving them direct drawing access to Druid. This would also make things easier for any future standardization across editors. 
  - HTML+CSS (and then use `onclick="wasm-defined-function"`) would theoretically work, but I'm skeptical at how well it would integrate with how we are doing UI and would likely need to bring in a *large* library to embed it in Lapce? I think a simpler UI approach would work best.

**Comment by informaticalex** [comment]
Seconding @newcomertv's **Preview Window**.

Possible examples of functionality (from 'simplest' to 'most difficult') are:
1. GitHub's `Write` vs `Preview` tabs (like when commenting in this thread)!
2. Markdown viewer like GNOME's [Apostrophe](https://gitlab.gnome.org/World/apostrophe)
3. Compiler to .pdf/HTML like R's [knitr](https://yihui.org/knitr/)
4. Mimic [org-mode](https://orgmode.org/) with custom syntax

Such a plugin would wider Lapce's appeal to users who need to publish written works, as well as develop code (or, is this even an objective)?

**Comment by Th3Whit3Wolf** [comment]
A good package metadata file. Vscode requires extension declare their capabilities in their `package.json` and can use this data to display menu for their extension with descriptions and help tooltips on hover. [Vscode's API](https://code.visualstudio.com/api/extension-guides/overview) I think is probably worth looking at in general since it's designed for many different kinds of plugins with different feature set and is pretty mature at this point. I think this kind of api encourages good documentation, having possible plugin configuration settings predefined allows for type checking/linting of the user configuration settings, and would give lapce the ability to more easily render the plugin settings in an intuitive way as well as other aspects of the plugin.

Below are some examples of json settings and how vscode renders them ([all examples are taken from vsocde's api reference site](https://code.visualstudio.com/api/references/contribution-points) ).

#### Example 1

```yaml
{
  "contributes": {
    "commands": [
      {
        "command": "extension.sayHello",
        "title": "Hello World",
        "category": "Hello",
      }
    ]
  }
}
```

turns into

![commands](https://user-images.githubusercontent.com/48275422/131222619-eb30d259-9a53-49d6-97a7-38886c218560.png)

#### Example 2

```yaml
{
  "contributes": {
    "configuration": {
      "title": "TypeScript",
      "properties": {
        "typescript.useCodeSnippetsOnMethodSuggest": {
          "type": "boolean",
          "default": false,
          "description": "Complete functions with their parameter signature."
        },
        "typescript.tsdk": {
          "type": ["string", "null"],
          "default": null,
          "description": "Specifies the folder path containing the tsserver and lib*.d.ts files to use."
        }
      }
    }
  }
}
```

turns into

![configuration](https://user-images.githubusercontent.com/48275422/131222636-50c763dc-2d96-4361-bdd8-4c23407289da.png)

#### Example 3

```yaml
{
  "gitMagic.blame.heatmap.location": {
    "type": "string",
    "default": "right",
    "enum": ["left", "right"],
    "enumDescriptions": [
      "Adds a heatmap indicator on the left edge of the gutter blame annotations",
      "Adds a heatmap indicator on the right edge of the gutter blame annotations"
    ]
  }
}
```

turns into

![settings-ui-enum](https://user-images.githubusercontent.com/48275422/131222688-dcea4a34-388c-4f89-985d-edb382c927b2.png)

#### Example 4

```yaml
{
  "contributes": {
    "keybindings": [
      {
        "command": "extension.sayHello",
        "key": "ctrl+f1",
        "mac": "cmd+f1",
        "when": "editorTextFocus"
      }
    ]
  }
}
```

turns into (notice the Ctrl+F1 in top right corner of prompt)

![keybindings](https://user-images.githubusercontent.com/48275422/131222872-72f995e3-4329-49cc-a22c-2142e12471f0.png)

**Comment by mayel** [comment]
My #1 would be Language Servers like https://github.com/elixir-lsp/elixir-ls

**Comment by theAkito** [comment]
I personally have a different story about plugin development. If it does not fit into this discussion, please excuse this comment. 🙂

Many times, I wanted to improve an editor of some kind, like e.g. Visual Studio Code, Kate and other minor ones. Other software too, but I'll take editors as an example, since we are talking about an editor, here.

However, it only allowed creating a plugin in the most convoluted way (weird and hard to understand configurations) or it only allowed terrible tools like JavaScript (TypeScript) or Python. For example, Visual Studio Code is the editor I use 70% of my development time and I had lots to improve on that. I wanted to contribute. But it is so strutted on TypeScript, I did not find the motivation to contribute at all, because I prefer languages that are closer to the ground, i.e. one like the one this piece of software is written in. Documentation was also an issue, especially when some weird configurations are required and there is only about two sentences about configuration in the documentation regarding plugin development. Bummer.

Therefore, I wish for a good documented API, that is "natural" to use. Don't give me some code generator or force complex configuration onto my project. Just let me use the API, preferably like an every day library. Import stuff, call stuff and then compile your project and deploy the library into a folder or whatever.
Not sure if it is possible to do it the simple way I imagine, but it would be great, if that would be the case.

____

As for the API capabilities, please make it as open as possible. Do not close up some functionality on purpose, for philosophical reasons, except there is truly a hugely glaring & obvious issue with opening a certain aspect to be modified by anyone. For example, even a popular editor like VS Code has some weird limitations, which limits plugin development, which again limits the customisation capabilities, even though editors like IntelliJ have the same stuff already built-in and basically laugh at VS Code, because those abilities aren't even customisable in a plugin, let alone built-in...

____

As for looking at it from a user's perspective, many good points have already been mentioned here. Thank you all for that. I have not much to add.

One thing I would like to emphasize is theming. I'm not talking about bling-bling fancy NodeJS developer styled theming for no purpose other than looks and fanciness.
I am talking about functional theming, that helps people code better.

It has to be possible to change minute little details, because these are often the ones that have the biggest impact in the major picture of how a theme works. Changing one little detail in a theme might make it almost entirely worthless.

Another thing is a tiny feature, with a huge impact (*cough* VS Code still ain't doing it *cough*).
**Read-only mode.**

How is that so hard to implement for VS Code? IntelliJ does it naturally, without question. Damn you, VS Code.

Please, make it possible to force read-only mode on certain file views. For example, read-only mode for 3rd party libraries, which is the default behaviour in IntelliJ.

____

That's all I got for now.
I hope, this fits more or less into this discussion and was helpful.

Do not hesitate to give me feedback, if you have any! 😀

**Comment by dzhou121** [comment]
>I am talking about functional theming, that helps people code better.

Can you please describe this in more detail?

**Comment by KSXGitHub** [comment]
@theAkito 
The plugins would be in WASM, so you can use any language that compiles to WASM.

I think making the API too open would make it hard to avoid breaking change. VS Code limiting API capabilities has allowed its code to be changed, refactored, restructured to improve without worrying too much about compatibility. If you want a feature that isn't possible with given API, you could ask the Lapce developers to merge your PR or propose an API.

Can you speak more about "functional theming"?

I agree with read-only mode.

**Comment by ghishadow** [comment]
> To start with, it would be helpful to know, what plugin you desperately need as a user.

[Devcontainer](https://github.com/microsoft/vscode-dev-containers) support they recently published [spec](https://github.com/devcontainers/spec) and [CLI](https://github.com/devcontainers/cli), so it can become independent of Editor. It created prebuilt VM with all the extension/toolchain needed for project so used by many projects. I am planning to implement it using [krunvm](https://github.com/containers/krunvm), but it might take long time.

**Comment by moghaazi** [comment]
Brackets and indent guides colorization, it's native now in VS Code

![image](https://user-images.githubusercontent.com/49992538/175770705-901fda2d-b161-4e71-b819-a66c6111ff3a.png)

**Comment by moghaazi** [comment]
Add the ability create lists For example, I'll need to create a list of plugins for Rust, Vue, React, and themes so that when I'm working on a project using react.js, I can enable only the react plugins and disable the others to speed up the editor.

**Comment by slyshykO** [comment]
Very useful for me is an **outline** view.
Not sure if should it be a plugin or in the main codebase.
![image](https://user-images.githubusercontent.com/1575537/181169645-84cf872b-50d9-419e-84c9-c33cab981e32.png)

**Comment by MinusGix** [comment]
> Very useful for me is an **outline** view. Not sure if should it be a plugin or in the main codebase.  
  
I think this is probably be a Language Server feature, so you can open a separate issue for having it inbuilt to the editor if you wish.

**Comment by khuongduybui** [comment]
hi guys I want to make a mulit-language code linter / formatter plugin that utilizes [trunk.io](https://trunk.io/). Has anyone done a plugin like that? What interfaces do my plugin needs to expose in the WASM?

**Comment by panekj** [comment]
> hi guys I want to make a mulit-language code linter / formatter plugin that utilizes [trunk.io](https://trunk.io/). Has anyone done a plugin like that? What interfaces do my plugin needs to expose in the WASM?

There is no plugin API so it's not possible right now

**Comment by manaskarekar** [comment]
I'm sure this is already a WIP but some documentation showing example plugins would boost plugin development a lot. I apologize if this exists and I missed it!

I would also love to help with integrating any LSP languages.

**Comment by ConnorSMorrison** [comment]
I'd love for lapce to finish HTML tags itself. For example, when I type <body> it would fill in </body> behind the cursor. I think this should go for strings too like it does for brackets but that would probably be in the core.

**Comment by zyxkad** [comment]
- Add sidebar plugin search, It will be useful if we have many plugins

**Comment by aljaxus** [comment]
> Overall when it comes to plugins, I believe there are two kinds of capabilities:
> 
>     * System-based: some plugins need to execute commands at some point (a git plugin invoking git, a Docker plugin interacting with docker using the CLI, etc.). **This is the easiest capability to add for immediate use**
>       _Do not that vscode allows arbitrary command execution, so it's not something new on our side_

I would say the the docker API is quite easy to communicate with. It's basically a REST api. (I've developed some project interacting with it a while ago; ref [docker.js](https://gitplac.si/aljaxus/mark3/-/blob/master/app/src/plugins/docker.js) )

**Comment by nheuillet** [comment]
@aljaxus you're right, docker was not the best example for that, although I believe the point still stands

**Comment by aljaxus** [comment]
> @aljaxus you're right, docker was not the best example for that, although I believe the point still stands

Yes, sorry - my bad. I was going to say that I agree with you, as I would also like to see a docker extension added (the reason why I was searching for Docker in the issue). I got distracted with something else and just posted the reply without finishing it.

I fully agree with your comment.

---

To add to all this, I'm surprised that highlight for Markdown isn't present yet, or at least in AUR version of Lapce isn't.

**Comment by panekj** [comment]
> To add to all this, I'm surprised that highlight for Markdown isn't present yet, or at least in arch official repo version (0.2.0-1) of Lapce isn't.

it was just fixed https://github.com/lapce/lapce/pull/957

**Comment by dzhou121** [comment]
I'll close this now, because we've decided the direction of plugin API.

Further discussions about plugin ideas will be in plugin-ideas channel on [Discord](https://discord.gg/n8tGJ6Rn6D)

**Comment by Filgas08** [comment]
I recently started using lapce and the absence of a folding system for loops and functions makes it hard to work on long files.
I think it could be a pretty good feature to be able to fold individual brackets pairs.

**Comment by panekj** [comment]
> I recently started using lapce and the absence of a folding system for loops and functions makes it hard to work on long files.
> I think it could be a pretty good feature to be able to fold individual brackets pairs.

This doesn't relate to plugin support, please create new issue for feature request

**Comment by keepsimple1** [comment]
Is the Plugin support already settled? It's not clear from this thread. Where should I look for Plugin support info if I just get started with Lapce?

**Comment by panekj** [comment]
You can install plugins from extension tab in Lapce

**Comment by keepsimple1** [comment]
> You can install plugins from extension tab in Lapce

Thanks. Where is the Get Started info for plugins development?

**Comment by panekj** [comment]
https://docs.lapce.dev

**Comment by rocket-matt** [comment]
For me, there are 2 major plugins that are missing that are included in VSCode.  This stops me from using Lapce.  1: Vim bindings; and 2: Copilot support.

**Comment by panekj** [comment]
> 1: Vim bindings;

we have integrated Vi binds

> 2: Copilot support.

- Copilot is closed source
- it's not possible to present multiline ghost text like Copilot does

**Comment by rocket-matt** [comment]
I checked the command palette and plugins but couldn't see it the vim bindings.  Where are they?

I wonder if refact.ai is offering an API?  I think copilot-like systems are the future so Lapce should support multiline ghost text.  You're right about copilot being closed source.  I was hoping they had an API.

**Comment by panekj** [comment]
> I checked the command palette and plugins but couldn't see it the vim bindings. Where are they?

https://docs.lapce.dev/get-started/modal-editing

![image](https://github.com/lapce/lapce/assets/50457605/fafe7ec2-e053-47a2-9fdf-1bf06d7fb81d)
![image](https://github.com/lapce/lapce/assets/50457605/4a91ff7a-6a40-472f-89e7-1cb121d4da6f)
