### ISSUE TITLE
Memory hogger on Mac M1

### ISSUE THREAD

**Issue by singhsaubhik** [lapce/lapce#77]
This application very fast starts cosuming a large chunk of RAM, attaching screenshot

**System Specification**
Macbook Air (M1 2020)
Chip Apple M1
Memory 16 GB

**Screenshot**
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/30568908/156492664-41c84ff8-043c-4bb1-99a6-098da8a40848.png">

**Comment by oleid** [comment]
Would you describe what you are doing after starting the application? Anything particular like opening a rust project or something along the line?

**Comment by SinghSaubhik** [comment]
> Would you describe what you are doing after starting the application? Anything particular like opening a rust project or something along the line?

I was playing around, opened a small rust project and typing some code realized some lag and frame drops. When analysed using Activity Monitor saw it was consuming more than 5gb of Ram.

**Comment by ghishadow** [comment]
One thing i noticed is if you installed rust plugin, then rust analyzer takes huge memory https://github.com/rust-analyzer/rust-analyzer/issues/5728 https://github.com/rust-analyzer/rust-analyzer/issues/1252 https://github.com/rust-analyzer/rust-analyzer/issues/9470 https://github.com/rust-analyzer/rust-analyzer/issues/11325 while indexing but after that memory usage get better

**Comment by hasali19** [comment]
I'm also getting very high memory usage on Windows when typing (without rust analyzer). I can consistently reproduce this by opening a file and holding down a key on the keyboard to fill up the editor. Once a line is full, move to the next line and keep entering text. After a few lines, the memory usage will suddenly start to increase significantly and keep increasing linearly as the editor fills. Interestingly, the memory only increases while the text fits on the screen - if it starts scrolling horizontally then it stops increasing, but starts again when I move to the next line.

**Comment by arcoleo** [comment]
I get similar behavior on a first generation Mac M1 with 16G ram.  I created a folder with a single file in it, `test1.txt`. The contents are `Testing Lapce`.

Lapce takes 1.45G.  I add the line `Hello, world!` and memory climbs to 2G and slowly creeps up from there.

**Comment by zyxkad** [comment]
I am on `Apple M1 Pro`, MacOS 12.1.
This issue is not happen

**Comment by panekj** [comment]
Memory now should slowly raise based on the actual usage (typing, etc.)
Tested on M1

**Comment by jianshu93** [comment]
I also have about 300-400M memory usage after installing rust code analyzer. However I think this is still much larger than others, for example visual studio code. The bad thing is when you open a second window, memory requirement doubles, which is very strange to me because it is still a rust project, why consuming double memory?

Thanks,

Jianshu

**Comment by jayzhan211** [comment]
![Screenshot 2023-06-20 at 21 32 46](https://github.com/lapce/lapce/assets/15869383/809e743a-911d-4b9d-b6fd-31aa14fdb0bb)

Starting RA server consume tons of memory, they are still there even I force quit VSCode. The memory usage is crazy. I did not have the same issue on another small project, is it because there are so many crates used and they are pre-indexing so they consume so much ram? Is there an option to lazily index the necessary crate only if I need it?
