### ISSUE TITLE
Editor sometimes blank when opening files

### ISSUE THREAD

**Issue by superlou** [lapce/lapce#823]
When opening certain files (which contain code) on the latest Windows nightly and 0.1.3, the editor is blank.

![image](https://user-images.githubusercontent.com/709695/179739844-41c9f134-5841-416c-8847-0dc6f8d774ee.png)

Initially I thought it was something to do with C files, but now I think maybe there is some character in certain files that causes it to abort. Other C files load fine, and it's consistent with specific files. Is there a way to turn on diagnostic information to determine what might be the problem? There is not information printed to the terminal.

**Comment by MinusGix** [comment]
If this is with clangd installed, then try turning that off and opening the file. (I don't expect this to do anything, but just in case)  
I'd also try copying the file, then cutting out half of it. If it still occurs, then cut out another half. Repeat until you get some minimal file that does it. Perhaps there's some weird character messing with the rendering? If so, then this method would help isolate it.  
How long is the file? I think I remember an old bug with failing to render very large files, though I don't expect that to be the cause here.

**Comment by superlou** [comment]
I initially had the clangd plugin installed but uninstalled it and had the same behavior. Unfortunately the file has some proprietary info in it, so I'll see if I can play the manual binary search myself to find the culprit. It's happening for a file that's only 214 lines, so I doubt it's a length issue.

**Comment by MinusGix** [comment]
Okay, thanks.  
I just realized that one place I've seen similar behavior is when opening a binary file (ex: the lapce binary) inside of lapce. You'll get a similar no output at all, despite expecting that there should be some renderable text inside of there. So, that does make me further believe there might be some weird special characters. (Though, this of course isn't desirable behavior)

**Comment by superlou** [comment]
Found it and made a minimal example (shown in Notepad++):

![image](https://user-images.githubusercontent.com/709695/179742979-e0168a1e-7b4b-4f88-85ff-c810845bb437.png)

It's the copyright symbol. File is attached with extension renamed to ".txt" to allow upload to Github.

[copyright_symbol.txt](https://github.com/lapce/lapce/files/9140727/copyright_symbol.txt)

**Comment by MinusGix** [comment]
(The issue was that the copyright symbol was from extended ascii, which isn't valid utf8.)
