### ISSUE TITLE
Slow/Bad internet can make Lapce take a bit to start

### ISSUE THREAD

**Issue by MinusGix** [lapce/lapce#900]
My internet went out yesterday, and when starting Lapce it would take a bit. I imagine was this due to network requests on startup, like for plugins.  
The internet likely wasn't yet 'completely out' so it probably kept retrying. When I just simply disconnected the internet, it did start immediately.  
However it should not block the startup of the editor even if the internet is absurdly slow or dropping most of the data.

**Comment by bbrabbitt** [comment]
It's because the new code for updating plugin information for installed and uninstalled plugins unfortunately blocks the main thread. I added this for updating the plugin list after plugin installations or upgrades but it's also called when the editor is starting. I'm considering an async way to do this but since ctx cannot be moved into the thread I'm trying to at least prevent calling it when the editor is starting.

https://github.com/lapce/lapce/blob/af9277db365a1eab201b92c0490f942f75477992/lapce-ui/src/tab.rs#L945-L972

**Comment by bbrabbitt** [comment]
Actually may be it's better to move it into proxy instead of on UI thread.

**Comment by MinusGix** [comment]
Probably want to wait until https://github.com/lapce/lapce/pull/893 before moving it to the proxy.
