### ISSUE TITLE
Lapce not rendering properly

### ISSUE THREAD

**Issue by Imsanskar** [lapce/lapce#908]
I am currently having the issue where rendering is not proper and I get this error while launching lapce.
```
(lapce:95868): GLib-GIO-CRITICAL **: 17:09:24.345: This application can not open files.
```
![image](https://user-images.githubusercontent.com/42579138/182024081-2270cee6-e2d6-4df0-babf-1ae732b96b65.png)

**Comment by MinusGix** [comment]
(The warning GLib gives doesn't matter, it is just one that hasn't been silenced with an easy fix)  
- Is this on 0.13?  
- What OS are you using?  

Try installing a font like Cascadia Code / Cantarell Regular / Liberation Sans, (the first being the default, I believe, and the others being fallbacks) to see if that fixes it. (Though, if this is occurring due to a missing font then that means we need to expand our fallbacks probably)

**Comment by panekj** [comment]
Closing as stale
