### ISSUE TITLE
font/settings: Sluggish performance upon editing the font family in Editor Settings.

### ISSUE THREAD

**Issue by schwrzstrbn** [lapce/lapce#918]
The previous problems were solved but it did not include the Editor Settings -> Font Family.
It produces a sluggish performance when editing the Font family in Editor settings, barely usable when the bug is reproduced.

![image](https://user-images.githubusercontent.com/45195351/182289972-ee71a5eb-b852-4a65-8cff-defae2a9cbac.png)

**Comment by schwrzstrbn** [comment]
Sudden spikes in cpu usage when editing Editor Settings.

![image](https://user-images.githubusercontent.com/45195351/182290393-aeac5b40-b35b-44ed-a29e-21b813511f2b.png)

**Comment by schwrzstrbn** [comment]
And after closing lapce, 

![image](https://user-images.githubusercontent.com/45195351/182290595-d8d91ed9-f043-4b86-a97d-3d2cc851c1bd.png)

**Comment by StoyK** [comment]
I encountered the same problem when I tried to leave the font family field empty so that it uses the system default, as said in the description.

My guess on why this happens is that when you leave the font family field empty, it doesn't remove the field in the settings.toml file, it just sets it to an empty string. So it would be reasonable to assume that the editor keeps trying to open a font with an "" name which doesn't exist. 
![image](https://user-images.githubusercontent.com/67196527/188288783-51373cc5-8878-43e2-8b4f-696015a8b1fc.png)

The fix to the issue is manually removing the font-family field in the settings file, which makes the editor revert to system defaults

**Comment by DuckDuckWhale** [comment]
Looks like this is fixed for me. Did #1030 forget to close the issue?

**Comment by schwrzstrbn** [comment]
> Looks like this is fixed for me. Did #1030 forget to close the issue?

Well yeah, i'm closing this now.

**Comment by filipencopav** [comment]
I tried to escape by pressing tab, it inserted a literal tab character, and it lagged just like the author of the issue describes it.

Isn't there a reason for this resource hogging and intensive CPU usage? It's trying to do something, for an indefinite amount of time. Maybe there should be a limit check, or maybe it should validate the input before doing more operations on it?
