### ISSUE TITLE
How to Support PHP LSP

### ISSUE THREAD

**Issue by mztlive** [lapce/lapce#921]
I Need Use Lapce Coding.
But, I don`t know How to Use PHP Language Server Proto

**Comment by panekj** [comment]
Someone has to make plugin that implements PHP LSP

**Comment by nheuillet** [comment]
In order to do this, you need:
- A PHP LSP server
- A PHP LSP plugin for Lapce. 

You can find examples of such plugins here:
[lapce-go](https://github.com/nheuillet/lapce-go)
[lapce-cpp-clangd](https://github.com/panekj/lapce-cpp-clangd)

While there is no clear documentation yet (the plugin API is still in its infancy, although it's the next priority and should be addressed very soon), most of the code should be straightforward.
If you have any questions regarding any part though, feel free to ping in the discord, or in this issue!

**Comment by Hasnayeen** [comment]
There is a PHP LSP plugin now for lapce. [Github link](https://github.com/dajoha/lapce-php-intelephense)

Install the plugin from lapce plugin menu: PHP (Intelephense)
Install the lsp server: `npm i intelephense -g`
Check the path to binary: `whereis intelephense`
Add the path to plugin settings in lapce: Path to Intelephense executable

P.S: it takes a while to index a project first time
